# This is a basic workflow to help you get started with Actions

name: CI

# Triggers the workflow on push request
# events but only for the master branch
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v1
      - uses: paambaati/codeclimate-action@v2.5.7
